""" phrases = [
    "this kills the",
    "came here to say this",
    "this. so much this",
    "so much this",
    "thanks for the gold",
    "thanks for the gold, kind stranger",
    "thanks for the gold, stranger",
    "rip my inbox",
    "am i the only one",
    "does anyone else",
    "relevant xkcd",
    "why is this so far down",
    "there are dozens of us",
    "i know this will get buried",
    "i know i'm going to get downvoted for this",
    "ayy lmao",
    "we did it, reddit",
    "my highest rated comment is about",
    "edit: a word"] """
